### ISSUE TITLE
Null pointer exception when editing an existing template and trying to save it as a new template

### ISSUE THREAD

**Issue by jquinss** [jquinss/QuickText#9]
A null pointer exception appears when editing an existing template and trying to save it as a new template.
Also, the "Save" button in the HTML template does not get enabled.

**Comment by jquinss** [comment]
Caused by: java.lang.NullPointerException
	at controllers.PlainTextEditorController.saveNewFile(PlainTextEditorController.java:28)
	at controllers.TextEditorController.saveAs(TextEditorController.java:111)

**Comment by jquinss** [comment]
folderTreeItem initialization was missing.
Added missing initialization of the folderTreeItem
